defaults:
  - _self_
  - logdir: none
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

workdir: ${hydra:runtime.cwd}
dataset:
  name: disease
  vectorizer: sentencepiece
  vocab_size: null
gene: null
control: false
