defaults:
  - _self_
  - logdir: none
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

dataset:
  name: capsule
num_val: 500
num_test: 1000
n_clusters: 512
fraction_covered: 10
